---
author: Tarcísio Giroldo
return-address: 
  - Musterstr. 12
  - 34567 Musterstadt
address:
  - Robert Nuske
  - Hauptstr. 31
  - 30167 Hannover
  - Germany
  
subject: Some jobs
opening: Dear HR,
closing: Yours truly,
signature: Tarcísio Giroldo

output: komaletter::komaletter
---

I'm a front-end software engineer with over 6 years of experience across several types of business and a bioinformatics and functional programming enthusiast.

During my BSc in biomedical informatics I worked as a intern researcher in bioinformatics where I gained expertise in data analysis using R, more specifically ggplot2, tidyr, dplyr, bioconductor packages(like limma and GEOQuery), and the creation of dashboards using Shiny.

During my graduation as a software engineer I gained knowledge using C, C++, Java, PostgreSQL.

In my first job as a fullstack software engineer at SmartEnvios I built scraping bots for the postal service of Brazil (known as Correios). The monitoring process was done using PM2 and the deploying of these services using AWS like LightSail, EC2, S3.
In this position I was responsible for developing, coding and deploying.

In my second job as a fullstack software engineer at Softwrap,  I worked with React and React Native, Node.js, Firebase and Docker, I was responsible to coordinate a specific team for the development of a hybrid application using React Native and Firebase for meal tickets from a disclosed company and created a pixel perfect application for accountability of accounting firms.


In my third job  as a frontend software engineer at Dasa, I worked only with React and its ecosystem (Styled-components, Context API, Hooks, React Testing Library and Ant Design). In this project achieved the highlights of my career building a tracking and management app for genomic testing (like NIPT - Non-Invasive Prenatal Testing and MLPA - Multiplex Ligation-dependent Probe Amplification) and furthermore, the development of  a LIMS application where users can generate reports and create their own analysis, check the lab samples between processes, and ask for additional testing or samples (in specific cases cancelling samples).
I was responsible for the design system and during the process I became responsible for the technical debt and improving the test coverage in frontend.
I’ve also worked on new features with the stakeholders and product team and fixed bugs reported by the QA team.
Some of the highlights included eliminating  the technical debt in full, improving the tests coverage up to 80% and the integration with Ant Design to the Dasa design system. Refactoring of all the components to ES6+, create a code standard for maintaining these components and reduce the  integration time by correctly configuring our Jenkins file with our guidelines.

In my current position at  Spocket I've been working in an international company as a frontend software engineer using React and its ecosystem (ES6+, Styled-components, Hooks, Context API, Redux, Jest and React Testing Library),  in a specific application for dropshipping and ecommerce, and I'm currently in charge of eliminating  the technical debt, improving our tests coverage on frontend, refactoring  components (class components to functional components), and making sure that the team will follow our handbook. Working in new features by demands scalated by the product team, fixed bugs finded by QA and CS team.

I have extensive experience working with agile development (scrum) using Jira or Zenhub.
I'm also a backend developer just for fun using Express, Nest.js and Fastify.
And I have experience with Next.js for SSR or SSG, Gatsby and Vite for tooling.
As a side skill I have a great knowledge of Linux systems (shell scripting) and configuring and using docker for maintaining environments.

As a hobby I enjoy spending time with my family and my dog ​​and also hanging out with my friends. I am a communicative and empathetic person and I always try to understand the other side of the conversation. I really appreciate studying new techs for frontend and functional programming (right now I'm learning Elixir and Phoenix).

I firmly believe that I’d be a great addition to the team. Thanks for taking the time to review my application.


