---
author: Tarcísio Giroldo
subject: Application for Frontend Software Engineer role
opening: Dear HR,
closing: Yours truly,
signature: Tarcísio Giroldo

output: komaletter::komaletter
---

I'm a front-end software engineer with over 6 years of experience across several types of business and a bioinformatics and functional programming enthusiast.

During my BSc in biomedical informatics I worked as a intern researcher in bioinformatics where I gained expertise in data analysis using R, more specifically ggplot2, tidyr, dplyr, bioconductor packages(like limma and GEOQuery), and the creation of dashboards using Shiny
I had classes such as Algorithm and Data Structures, Object Orient Programming, Databases and SQL, Machine Learning, Operating Systems and Distributed Systems.
I also gained knowledge learning and using C, C++, R, Java and PostgreSQL.

At Spocket, I have had the privilege to work as a Frontend Engineer, utilizing React and its comprehensive ecosystem. I have contributed to the development of new features aligned with the company's coding standards and best practices. Notably, I have refactored legacy components to modern ES6+ standards, improving the maintainability and performance of the codebase. In addition, I created a guide for unit testing to facilitate effective collaboration within the team. My role also involved the successful implementation of a new CI/CD pipeline using Github Actions, AWS S3, and Cloudfront, resulting in streamlined deployment processes and improved efficiency.

My tenure at Dasa as a Software Engineer provided me with the opportunity to work extensively with React and associated technologies. I was responsible for developing new features, ensuring bug-free performance, and implementing refactoring strategies to enhance the design system's developer experience. My commitment to quality was demonstrated through the creation of a comprehensive unit testing suite, achieving an impressive 80% test coverage. Additionally, I spearheaded improvements to the CI/CD pipeline, leveraging Jenkins to enhance reliability and reduce processing time.

During my time as a Full Stack Engineer at Softwrap, I excelled in coordinating a dedicated team focused on crafting a seamless hybrid application using React Native and Firebase. Leading this team of 3 developers, I not only delivered on project goals but also nurtured the growth of junior team members through mentorship and guidance. One of my significant accomplishments was creating a pixel-perfect React Native application for the meticulous accounting needs of the firms, showcasing my dedication to precision and attention to detail.

In my previous role at SmartEnvios, I demonstrated my proficiency in a broader technology stack, handling full-stack development using React, Gatsby, TailwindCSS, Node.js, PostgreSQL, MongoDB, and Docker. I successfully contributed to the creation of the company's website, developed web scraping solutions, and implemented efficient deployment strategies.

As a dedicated learner, I continually invest time in expanding my skillset. Currently, I am learning Elixir and Phoenix to further enrich my programming capabilities. My holistic approach to development, collaborative spirit, and proactive problem-solving make me confident that I can contribute effectively to [Company Name]'s ongoing success.

Thank you for considering my application. I look forward to the opportunity to discuss how my experience aligns with your team's goals in more detail.


In my professional journey, I have cultivated a diverse set of skills that span various technology domains. With over 6 years of experience, Javascript is not just a programming language for me; it's my native tongue. I embarked on this journey in 2013, gradually transitioning into working professionally with it, particularly on the frontend. I have a robust command over React and its ecosystem, employing styled-components, Ant Design, and TailwindCSS for sophisticated stylization. My expertise extends to state management using Context API, Redux, Redux Toolkit (RTK), and Zustand. I've harnessed the power of React Query from Tanstack for asynchronous state management and used axios and fetch APIs to interact with diverse backends. I've championed unit testing through React Testing Library (RTL) and Jest, and I've harnessed the capabilities of Next.js for SSR and ISR while also creating blog sites with Gatsby.

But my skill set doesn't stop at Javascript. I've delved into Typescript, leveraging Zod for schema validation, and Prisma for database handling in conjunction with Next.js, NestJS, and Fastify. Rust has also captured my attention, becoming my preferred side language for personal projects. I'm adept at using the tokio runtime for asynchronous programming and working with frameworks like actix-web, axum, gotham, and tide. I've utilized ORMs such as sqlx and diesel, enhancing efficiency and maintainability. My exploration extends to Elixir, where I've honed skills in creating APIs and fullstack applications with Phoenix, handling databases with Ecto, and utilizing code analysis tools like credo and dialyxir.

In the realm of HTML/CSS, I'm skilled in creating semantic and accessible web applications, meticulously following a11y guidelines. I'm experienced in CSS, implementing the BEM methodology to enhance code organization and maintainability. My proficiency extends to the domain of data manipulation with R, where I've leveraged Bioconductor packages like limma and GEOQuery, conducted data wrangling and visualization with ggplot2, tidyr, and dplyr, and orchestrated integrations with both relational and non-relational databases.

My journey also encompasses DevOps practices, where I've embraced Docker to streamline application deployment. I've orchestrated continuous integration and deployment using Jenkins, CircleCI, and Github Actions, while also utilizing cloud platforms like Cloudflare, Netlify, and Vercel for personal projects. I've ventured into code quality assessment with SonarQube and security enforcement through Fortify. My familiarity with AWS - EC2, S3, Cloudfront, LightSail, and Amplify - exemplifies my proficiency in cloud infrastructure management. Additionally, I'm in the process of mastering Terraform and Ansible to further enhance my DevOps arsenal.

In the realm of databases, my experience spans both relational and non-relational systems, including PostgreSQL, MongoDB, and the integration of Firebase and Supabase into various projects. Fluent in Portuguese as a native speaker and proficient in English at a C1 level, I thrive in diverse linguistic environments. My multifaceted skill set reflects my commitment to staying at the forefront of technology and my unwavering passion for creating impactful solutions.
As a hobby I enjoy spending time with my family and my dog ​​and also hanging out with my friends. I am a communicative and empathetic person and I always try to understand the other side of the conversation. I really appreciate studying new techs for frontend and functional programming (right now I'm learning Elixir and Phoenix).

I firmly believe that I’d be a great addition to the team. Thanks for taking the time to review my application.


