---
name: Tarcísio
surname: Giroldo
position: "Engenheiro de Software Senior"
www: "giroldo.dev"
email: "tsgiroldo@gmail.com"
github: girordo
linkedin: targiroldo
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 7d34eb
aboutme: "Eu sou um engenheiro de software senior com mais de 6 anos de experiência em diversos tipos de negócios. Tenho foco em React e seu ecossistema. Tenho experiência em testes unitários, reescrita e refatoração de aplicações React e desempenho no frontend. Também gosto de estudar novas tecnologias como Rust e Elixir. No meu tempo livre, gosto de passar tempo com meu cachorro, família e amigos."
docname: Resume
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("data","data-pt-br.R"))

```

# Experiência

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} -- {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Educação

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} -- {endYear}",.na = ""),
    where = where
  )

```

\pagebreak

# Competências

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills,
    why = detail
  )

```