name: CI for CV
on:
  push:
    paths:
    - .github/workflows/ci.yml
    - 'data/**'
    branches:
      - main 
  workflow_dispatch:
    
permissions: write-all

jobs:
  build:
    name: Creation of resume in en and pt-br
    runs-on: ubuntu-latest
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Installing texlive
        run: |
          sudo apt-get -y update
          sudo apt-get install -y texlive-base texlive-latex-base
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-fonts-extra

      - name: Render the resumes
        run: |
          Rscript -e "files_list <- c("data-driven-resume.Rmd", "data-driven-resume-pt-br.Rmd", "data-driven-resume-pt-br-small.Rmd", "data-driven-resume-small.Rmd"); for (i in files_list) {rmarkdown::render(input = file.path(getwd(), i), params = list(work_dir = getwd()))}"
          mv *.pdf resumes/

      - name: Rendering cover letter
        run: |
          Rscript -e "remotes::install_github('rnuske/komaletter', upgrade = 'always', dependencies = TRUE)"
          Rscript -e "rmarkdown::render(input = file.path(getwd(), 'cover-letter.Rmd'))"
          Rscript -e "rmarkdown::render(input = file.path(getwd(), 'cover-letter-formal.Rmd'))"
          Rscript -e "rmarkdown::render(input = file.path(getwd(), 'cover-letter-formal-pt-br.Rmd'))"
          Rscript -e "rmarkdown::render(input = file.path(getwd(), 'cover-letter-pt-br.Rmd'))"
          mv *.pdf cover-letter/ 

        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am "add the cv in english and pt-br files to the directory of the repository"
          git push