name: CI for CV
on:
  push:
    paths:
    - .github/workflows/ci.yml
    - 'markdowns/**'
    - 'data/**'
    branches:
      - main        
permissions: write-all

jobs:
  build:
    name: Creation of resume in en and pt-br
    runs-on: ubuntu-latest
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Installing texlive
        run: |
          sudo apt-get -y update
          sudo apt-get install -y texlive-base texlive-latex-base
          sudo apt-get install -y texlive-latex-recommended
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-fonts-extra

      - name: Render the resumes
        run: |
          Rscript -e "rmarkdown::render(input = file.path(getwd(), 'data-driven-resume.Rmd'), params = list(work_dir = getwd()))"
          Rscript -e "rmarkdown::render(input = file.path(getwd(), 'data-driven-resume-pt-br.Rmd'), params = list(work_dir = getwd()))"
      
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am "add the cv in english and pt-br files to the directory of the repository"
          git push
