name: CI for CV
on:
  push:
    branches:
      - main        
permissions: write-all

jobs:
  build:
    name: Creation of resume in en and pt-br
    runs-on: ubuntu-latest
    container:
      image: mlampros/mycvitae:rstudiodev
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Render the resumes
        run: |
          Rscript -e "markdowns = file.path(getwd(), c('data-driven-resume.Rmd', 'data-driven-resume-pt-br.Rmd'))"
          Rscript -e "rmarkdown::render(input = markdowns, params = list(work_dir = getwd()))"
      
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -am "add the cv in english and pt-br files to the directory of the repository"
          git push
